language: go
go:
  - master

notification:
  email:
    - gcpedu@google.com
    - edcation4gcp@gmail.com

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    - COMMIT_AUTHOR_EMAIL: "education4gcp@gmail.com"
    - ENCRYPTION_LABEL: "18ca7b75201b"

script: ./deploy.sh

